version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "./pom.xml" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
  test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "./pom.xml" }}
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - store_test_results:
          path: target/surefire-reports

workflows:
  maven_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test
          requires:
            - hold
  version: 2.1
