version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "./pom.xml" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "./pom.xml" }}
  test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "./pom.xml" }}
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - store_test_results:
          path: target/surefire-reports
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "./pom.xml" }}
      - run:
          name: Build Artifact
          command: mvn package
      - run:
          name: Prepare artifacts folder
          command: mkdir /tmp/artifacts
      - store_artifacts:
          path: target/example.jar
          destination: example-artifact.jar
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2.1
  maven_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold
      - deploy:
          requires:
            - build

